# Database 365 Kata 'Yawm' (Tunggal) dalam Al-Qur'an
DATA_YAWM = {
    1: ("Al-Fatihah", 1, 4, "Maaliki Yawmi-d-Diin"),
    2: ("Al-Baqarah", 2, 8, "Bi-l-Yawmi-l-Aakhir"),
    3: ("Al-Baqarah", 2, 48, "Yawman laa tajzii nafsun"),
        # Lanjutan Database Yawm (4 - 50)
    4: ("Al-Baqarah", 2, 62, "Wa-l-Yawmi-l-Aakhir (Dan Hari Akhir)"),
    5: ("Al-Baqarah", 2, 85, "Yawma-l-Qiyaamah (Hari Kiamat)"),
    6: ("Al-Baqarah", 2, 113, "Yawma-l-Qiyaamah (Hari Kiamat)"),
    7: ("Al-Baqarah", 2, 123, "Yawman laa tajzii nafsun (Hari ketika tidak ada jiwa yang dapat membela)"),
    8: ("Al-Baqarah", 2, 126, "Wa-l-Yawmi-l-Aakhir (Dan Hari Akhir)"),
    9: ("Al-Baqarah", 2, 174, "Yawma-l-Qiyaamah (Hari Kiamat)"),
    10: ("Al-Baqarah", 2, 177, "Wa-l-Yawmi-l-Aakhir (Dan Hari Akhir)"),
    11: ("Al-Baqarah", 2, 203, "Fi ayyaamin ma'duudaat (Dalam beberapa hari yang terbilang)"),
    12: ("Al-Baqarah", 2, 212, "Ilaa Yawmi-l-Qiyaamah (Sampai Hari Kiamat)"),
    13: ("Al-Baqarah", 2, 249, "Laa thaaqata lana-l-Yawma (Tak ada kekuatan bagi kami hari ini)"),
    14: ("Al-Baqarah", 2, 254, "Min qabli an ya'tiya Yawmun (Sebelum datangnya suatu Hari)"),
    15: ("Al-Baqarah", 2, 259, "Labitstu yawman aw ba'da yawm (Aku telah tinggal sehari atau setengah hari)"),
    16: ("Al-Baqarah", 2, 281, "Wattaquu Yawman turja'uuna fiihi (Takutlah kalian pada hari kalian dikembalikan)"),
    17: ("Ali 'Imran", 3, 9, "Li-Yawmin laa rayba fiih (Pada hari yang tidak ada keraguan padanya)"),
    18: ("Ali 'Imran", 3, 25, "Li-Yawmin laa rayba fiih (Pada hari yang tidak ada keraguan padanya)"),
    19: ("Ali 'Imran", 3, 30, "Yawma tajidu kullu nafsin (Hari ketika setiap jiwa mendapati balasan)"),
    20: ("Ali 'Imran", 3, 55, "Ilaa Yawmi-l-Qiyaamah (Sampai Hari Kiamat)"),
    21: ("Ali 'Imran", 3, 77, "Yawma-l-Qiyaamah (Hari Kiamat)"),
    22: ("Ali 'Imran", 3, 106, "Yawma tabyadh-dhu wujuuh (Hari ketika ada wajah yang putih berseri)"),
    23: ("Ali 'Imran", 3, 155, "Yawma-l-taqa-l-jam'aan (Hari ketika dua pasukan bertemu)"),
    24: ("Ali 'Imran", 3, 161, "Bimaa gharra Yawma-l-Qiyaamah (Apa yang dikhianatinya pada hari kiamat)"),
    25: ("Ali 'Imran", 3, 166, "Yawma-l-taqa-l-jam'aan (Hari ketika dua pasukan bertemu)"),
    26: ("Ali 'Imran", 3, 180, "Yawma-l-Qiyaamah (Hari Kiamat)"),
    27: ("Ali 'Imran", 3, 185, "Yawma-l-Qiyaamah (Hari Kiamat)"),
    28: ("Ali 'Imran", 3, 194, "Yawma-l-Qiyaamah (Hari Kiamat)"),
    29: ("An-Nisa", 4, 59, "Wa-l-Yawmi-l-Aakhir (Dan Hari Akhir)"),
    30: ("An-Nisa", 4, 87, "Ilaa Yawmi-l-Qiyaamah (Sampai Hari Kiamat)"),
    31: ("An-Nisa", 4, 109, "Yawma-l-Qiyaamah (Siapa yang membela mereka pada hari kiamat?)"),
    32: ("An-Nisa", 4, 136, "Wa-l-Yawmi-l-Aakhir (Dan Hari Akhir)"),
    33: ("An-Nisa", 4, 159, "Yawma-l-Qiyaamah (Hari Kiamat)"),
    34: ("An-Nisa", 4, 162, "Wa-l-Yawmi-l-Aakhir (Dan Hari Akhir)"),
    35: ("Al-Ma'idah", 5, 3, "Al-Yawma akmaltu lakum dinakum (Pada hari ini telah Kusempurnakan agamamu)"),
    36: ("Al-Ma'idah", 5, 3, "Al-Yawma ya'isa-lladzina kafaru (Pada hari ini orang kafir telah putus asa)"),
    37: ("Al-Ma'idah", 5, 5, "Al-Yawma uhilla lakumu-th-thayyibaat (Pada hari ini dihalalkan bagimu yang baik)"),
    38: ("Al-Ma'idah", 5, 14, "Ilaa Yawmi-l-Qiyaamah (Sampai Hari Kiamat)"),
    39: ("Al-Ma'idah", 5, 36, "Min 'adzabi Yawmi-l-Qiyaamah (Dari azab Hari Kiamat)"),
    40: ("Al-Ma'idah", 5, 64, "Ilaa Yawmi-l-Qiyaamah (Sampai Hari Kiamat)"),
    41: ("Al-Ma'idah", 5, 69, "Wa-l-Yawmi-l-Aakhir (Dan Hari Akhir)"),
    42: ("Al-Ma'idah", 5, 109, "Yawma yajma'u-llahu-r-rusul (Hari ketika Allah mengumpulkan para Rasul)"),
    43: ("Al-Ma'idah", 5, 119, "Haadza Yawmu yanfa'u-sh-shadiqin (Ini adalah hari yang bermanfaat bagi orang jujur)"),
    44: ("Al-An'am", 6, 12, "Li-Yawmin laa rayba fiih (Pada hari yang tidak ada keraguan padanya)"),
    45: ("Al-An'am", 6, 15, " 'Adzaba Yawmin 'Adziim (Azab hari yang agung)"),
    46: ("Al-An'am", 6, 22, "Wa-Yawma nahsyuruhum jamii'a (Dan pada hari Kami mengumpulkan mereka semua)"),
    47: ("Al-An'am", 6, 73, "Wa-Yawma yaqulu kun fayakun (Dan pada hari Dia berkata: Jadilah!)"),
    48: ("Al-An'am", 6, 73, "Wa-lahu-l-mulku Yawma yunfakhu (Milik-Nya lah kerajaan pada hari sangkakala ditiup)"),
    49: ("Al-An'am", 6, 93, "Al-Yawma tujzawna 'adzaba-l-hun (Pada hari ini kamu dibalas dengan azab yang menghinakan)"),
    50: ("Al-An'am", 6, 128, "Wa-Yawma nahsyuruhum jamii'a (Dan pada hari Kami mengumpulkan mereka semua)"),
    # Lanjutan Database Yawm (51 - 100)
    51: ("Al-An'am", 6, 141, "Aatuu haqqahu Yawma hhashadih (Berikanlah haknya pada hari panen)"),
    52: ("Al-An'am", 6, 158, "Yawma ya'tii ba'du aayaati rabbik (Pada hari datangnya sebagian tanda-tanda Tuhanmu)"),
    53: ("Al-A'raf", 7, 14, "Ilaa Yawmi yub'atsuun (Sampai hari mereka dibangkitkan)"),
    54: ("Al-A'raf", 7, 32, "Khaalishatan Yawma-l-Qiyaamah (Khusus bagi mereka pada hari kiamat)"),
    55: ("Al-A'raf", 7, 51, "Fa-l-Yawma nansaahum (Maka pada hari ini Kami melupakan mereka)"),
    56: ("Al-A'raf", 7, 53, "Yawma ya'tii ta'wiiluhu (Pada hari datangnya kenyataan itu)"),
    57: ("Al-A'raf", 7, 59, " 'Adzaba Yawmin 'Adziim (Azab hari yang agung)"),
    58: ("Al-A'raf", 7, 163, "Wa-Yawma laa yasbituun (Dan pada hari mereka tidak beristirahat)"),
    59: ("Al-A'raf", 7, 163, "Yawma sabtihim syurra'a (Pada hari sabtu mereka, ikan-ikan muncul)"),
    60: ("Al-A'raf", 7, 167, "Ilaa Yawmi-l-Qiyaamah (Sampai Hari Kiamat)"),
    61: ("Al-A'raf", 7, 172, "An taquluu Yawma-l-Qiyaamah (Agar kamu tidak mengatakan pada hari kiamat)"),
    62: ("Al-Anfal", 8, 41, "Yawma-l-furqaan Yawma-l-taqa-l-jam'aan (Hari pemisahan, hari bertemunya dua pasukan)"),
    63: ("Al-Anfal", 8, 48, "Laa ghaaliba lakumu-l-Yawma (Tak ada yang dapat mengalahkanmu hari ini)"),
    64: ("At-Tawbah", 9, 3, "Yawma-l-Hajji-l-Akbar (Pada hari Haji Akbar)"),
    65: ("At-Tawbah", 9, 25, "Wa-Yawma Hunayn (Dan pada hari peperangan Hunain)"),
    66: ("At-Tawbah", 9, 35, "Yawma yuhmaa 'alayhaa (Pada hari ketika dipanaskan emas dan perak itu)"),
    67: ("At-Tawbah", 9, 36, "Yawma khalaqa-s-samawaat (Pada hari Dia menciptakan langit dan bumi)"),
    68: ("At-Tawbah", 9, 77, "Ilaa Yawmi yalqawnahu (Sampai hari mereka menemui-Nya)"),
    69: ("At-Tawbah", 9, 108, "Min awwali yawm (Sejak hari pertama)"),
    70: ("Yunus", 10, 15, " 'Adzaba Yawmin 'Adziim (Azab hari yang agung)"),
    71: ("Yunus", 10, 28, "Wa-Yawma nahsyuruhum jamii'a (Dan pada hari Kami mengumpulkan mereka semua)"),
    72: ("Yunus", 10, 45, "Wa-Yawma nahsyuruhum ka'an lam yalbatstsuu (Pada hari Dia mengumpulkan mereka, seolah mereka tidak tinggal kecuali sekejap)"),
    73: ("Yunus", 10, 60, "Bi-Yawmi-l-Qiyaamah (Tentang Hari Kiamat)"),
    74: ("Yunus", 10, 92, "Fa-l-Yawma nunajjiika bi-badanik (Maka pada hari ini Kami selamatkan badanmu)"),
    75: ("Hud", 11, 3, "Ilaa ajalin musamma (Sampai waktu yang ditentukan)"),
    76: ("Hud", 11, 8, "Yawma ya'tiihim laysa mashruufan (Pada hari azab itu datang, tidaklah dapat dielakkan)"),
    77: ("Hud", 11, 26, " 'Adzaba Yawmin aliim (Azab hari yang pedih)"),
    78: ("Hud", 11, 43, "Laa 'aashyima-l-Yawma (Tak ada yang melindungi hari ini)"),
    79: ("Hud", 11, 60, "Alaa Yawma-l-Qiyaamah (Ingatlah, pada hari kiamat)"),
    80: ("Hud", 11, 77, "Haadza yawmun 'ashyiib (Ini adalah hari yang sangat sulit)"),
    81: ("Hud", 11, 103, "Dzaalika Yawmun majmuu'u-llahu (Itulah hari ketika manusia dikumpulkan)"),
    82: ("Hud", 11, 103, "Wa-dzaalika Yawmun masyhuud (Dan itulah hari yang disaksikan)"),
    83: ("Hud", 11, 105, "Yawma ya'ti laa takallamu nafsun (Di hari itu tidak ada seorang pun yang berbicara)"),
    84: ("Yusuf", 12, 54, "Innaka-l-Yawma ladaynaa makiin (Sesungguhnya kamu hari ini punya kedudukan tinggi)"),
    85: ("Yusuf", 12, 92, "Laa tatsriiba 'alaykumu-l-Yawma (Tak ada cercaan bagimu hari ini)"),
    86: ("Ibrahim", 14, 18, "Fii Yawmin 'ashyiif (Pada hari angin bertiup kencang)"),
    87: ("Ibrahim", 14, 31, "Min qabli an ya'tiya Yawmun (Sebelum datangnya suatu hari)"),
    88: ("Ibrahim", 14, 41, "Yawma yaquumu-l-hisaab (Pada hari terjadinya perhitungan)"),
    89: ("Ibrahim", 14, 42, "Innamaa yu-akh-khiruhum li-Yawmin (Hanya saja Dia menangguhkan mereka sampai hari)"),
    90: ("Ibrahim", 14, 44, "Wa-andziri-nnaasa Yawma ya'tiihim (Dan berilah peringatan pada hari azab datang)"),
    91: ("Al-Hijr", 15, 35, "Ilaa Yawmi-d-Diin (Sampai Hari Pembalasan)"),
    92: ("Al-Hijr", 15, 36, "Ilaa Yawmi yub'atsuun (Sampai hari mereka dibangkitkan)"),
    93: ("Al-Hijr", 15, 38, "Ilaa Yawmi-l-waqti-l-ma'luum (Sampai hari waktu yang ditentukan)"),
    94: ("An-Nahl", 16, 25, "Yawma-l-Qiyaamah (Pada Hari Kiamat)"),
    95: ("An-Nahl", 16, 27, "Yawma-l-Qiyaamah (Pada Hari Kiamat)"),
    96: ("An-Nahl", 16, 63, "Fahuwa waliyyuhumu-l-Yawma (Maka setan menjadi pemimpin mereka hari ini)"),
    97: ("An-Nahl", 16, 80, "Yawma dha'nikum wa-Yawma iqaamatikum (Di hari perjalananmu dan hari diammu)"),
    98: ("An-Nahl", 16, 84, "Wa-Yawma nab'atsu min kulli ummatin (Dan hari ketika Kami bangkitkan dari tiap umat)"),
    99: ("An-Nahl", 16, 89, "Wa-Yawma nab'atsu fii kulli ummatin (Dan hari ketika Kami bangkitkan pada tiap umat)"),
    100: ("An-Nahl", 16, 92, "Ilaa Yawmi-l-Qiyaamah (Sampai Hari Kiamat)"),
    # Lanjutan Database Yawm (101 - 150)
    101: ("An-Nahl", 16, 111, "Yawma ta'tii kullu nafsin (Hari ketika setiap jiwa datang membela diri)"),
    102: ("An-Nahl", 16, 124, "Yawma-l-Qiyaamah (Pada Hari Kiamat)"),
    103: ("Al-Isra", 17, 13, "Yawma-l-Qiyaamah kitaaban (Pada hari kiamat sebuah kitab)"),
    104: ("Al-Isra", 17, 52, "Yawma yad'uukum (Hari ketika Dia memanggilmu)"),
    105: ("Al-Isra", 17, 58, "Qabla Yawmi-l-Qiyaamah (Sebelum Hari Kiamat)"),
    106: ("Al-Isra", 17, 62, "Ilaa Yawmi-l-Qiyaamah (Sampai Hari Kiamat)"),
    107: ("Al-Isra", 17, 71, "Yawma nad'uu kulla unaasin (Hari ketika Kami panggil setiap manusia)"),
    108: ("Al-Isra", 17, 97, "Yawma-l-Qiyaamah 'alaa wujuuhihim (Pada hari kiamat atas wajah-wajah mereka)"),
    109: ("Al-Kahfi", 18, 19, "Yawman aw ba'dha yawm (Sehari atau setengah hari)"),
    110: ("Al-Kahfi", 18, 47, "Wa-Yawma nusayyiru-l-jibaal (Dan hari ketika Kami jalankan gunung-gunung)"),
    111: ("Al-Kahfi", 18, 52, "Wa-Yawma yaqulu naaduu syurakaa-i (Dan hari ketika Dia berfirman: Panggillah sekutu-Ku)"),
    112: ("Al-Kahfi", 18, 105, "Yawma-l-Qiyaamah waznaa (Pada hari kiamat suatu timbangan)"),
    113: ("Maryam", 19, 15, "Wa-Yawma yub'atsu hayya (Dan pada hari ia dibangkitkan hidup kembali)"),
    114: ("Maryam", 19, 26, "Falan ukallima-l-Yawma insiyya (Maka aku tidak akan bicara pada hari ini dengan manusia)"),
    115: ("Maryam", 19, 33, "Wa-Yawma ub'atsu hayya (Dan pada hari aku dibangkitkan hidup kembali)"),
    116: ("Maryam", 19, 37, "Min masyhadi Yawmin 'Adziim (Dari pemandangan Hari yang Agung)"),
    117: ("Maryam", 19, 38, "Yawma ya'tuunanaa (Pada hari mereka datang kepada Kami)"),
    118: ("Maryam", 19, 38, "Adh-dhalalu-l-Yawma (Kesesatan pada hari ini)"),
    119: ("Maryam", 19, 39, "Wa-andzirhum Yawma-l-hasrah (Peringatkanlah mereka akan Hari Penyesalan)"),
    120: ("Maryam", 19, 75, "Yawma yarawna maa yuu'aduun (Pada hari mereka melihat apa yang dijanjikan)"),
    121: ("Maryam", 19, 85, "Yawma nahsyuru-l-muttaqiin (Hari ketika Kami kumpulkan orang bertakwa)"),
    122: ("Maryam", 19, 95, "Yawma-l-Qiyaamah fardaa (Pada hari kiamat seorang diri)"),
    123: ("Thaha", 20, 59, "Maw'idukum Yawmu-z-ziinah (Waktu pertemuanmu adalah hari raya)"),
    124: ("Thaha", 20, 64, "Wa-qad aflaha-l-Yawma (Dan sungguh beruntung hari ini)"),
    125: ("Thaha", 20, 100, "Yawma-l-Qiyaamah wizraa (Pada hari kiamat beban dosa)"),
    126: ("Thaha", 20, 101, "Yawma-l-Qiyaamah himlaa (Pada hari kiamat tanggungan)"),
    127: ("Thaha", 20, 102, "Yawma yunfakhu fi-sh-shuur (Hari ketika sangkakala ditiup)"),
    128: ("Thaha", 20, 102, "Wa-nahsyuru-l-mujrimiin Yawma-idzin (Dan Kami kumpulkan pendosa pada hari itu)"),
    129: ("Thaha", 20, 104, "In labitstum illaa yawmaa (Kamu tidak tinggal kecuali sehari saja)"),
    130: ("Thaha", 20, 124, "Yawma-l-Qiyaamah a'maa (Pada hari kiamat dalam keadaan buta)"),
    131: ("Thaha", 20, 126, "Wa-kadzaalika-l-Yawma tunsaa (Dan demikian pula hari ini kamu dilupakan)"),
    132: ("Al-Anbiya", 21, 47, "Yawma-l-Qiyaamah falaa tudzlamu (Pada hari kiamat maka tidak dizalimi)"),
    133: ("Al-Anbiya", 21, 104, "Yawma nathwi-s-samaa-a (Hari ketika Kami gulung langit)"),
    134: ("Al-Hajj", 22, 2, "Yawma tarawnahaa (Hari ketika kamu melihatnya)"),
    135: ("Al-Hajj", 22, 9, "Yawma-l-Qiyaamah 'adzaba-l-hariiq (Pada hari kiamat azab yang membakar)"),
    136: ("Al-Hajj", 22, 17, "Yawma-l-Qiyaamah inna-llaha (Pada hari kiamat sesungguhnya Allah)"),
    137: ("Al-Hajj", 22, 47, "Wa-inna yawman 'inda rabbik (Dan sesungguhnya sehari di sisi Tuhanmu)"),
    138: ("Al-Hajj", 22, 55, "Aw ya'tiyahum 'adzabu Yawmin 'aqiim (Atau datang azab hari yang mandul/kehancuran)"),
    139: ("Al-Hajj", 22, 69, "Yawma-l-Qiyaamah fiimaa kuntum (Pada hari kiamat terhadap apa yang kamu perselisihkan)"),
    140: ("Al-Mu'minun", 23, 16, "Innakum Yawma-l-Qiyaamah (Sesungguhnya kamu pada hari kiamat)"),
    141: ("Al-Mu'minun", 23, 65, "Laa taj-aruu-l-Yawma (Janganlah kamu berteriak minta tolong hari ini)"),
    142: ("Al-Mu'minun", 23, 100, "Ilaa Yawmi yub'atsuun (Sampai hari mereka dibangkitkan)"),
    143: ("Al-Mu'minun", 23, 111, "Inni jazaytuhumu-l-Yawma (Sesungguhnya Aku memberi balasan pada mereka hari ini)"),
    144: ("Al-Mu'minun", 23, 113, "Labitstnaa yawman aw ba'dha yawm (Kami tinggal sehari atau setengah hari)"),
    145: ("An-Nur", 24, 2, "Wa-l-Yawmi-l-Aakhir (Dan Hari Akhir)"),
    146: ("An-Nur", 24, 24, "Yawma tasyhadu 'alayhim (Hari ketika lidah mereka menjadi saksi)"),
    147: ("An-Nur", 24, 37, "Yakhaafuuna Yawman (Mereka takut akan suatu hari)"),
    148: ("An-Nur", 24, 64, "Wa-Yawma yurja'uuna ilayh (Dan hari ketika mereka dikembalikan kepada-Nya)"),
    149: ("Al-Furqan", 25, 17, "Wa-Yawma nahsyuruhum (Dan hari ketika Kami mengumpulkan mereka)"),
    150: ("Al-Furqan", 25, 22, "Yawma yarawna-l-malaa-ikah (Hari ketika mereka melihat para malaikat)"),
    # Lanjutan Database Yawm (151 - 200)
    151: ("Al-Furqan", 25, 25, "Wa-Yawma tasyaqqaqu-s-samaa-u (Dan hari ketika langit pecah)"),
    152: ("Al-Furqan", 25, 26, "Al-mulku Yawma-idzin al-haqqu (Kerajaan pada hari itu adalah kebenaran)"),
    153: ("Al-Furqan", 25, 27, "Wa-Yawma ya'adh-dhudh-dhaalimu (Dan hari ketika orang zalim menggigit tangannya)"),
    154: ("Al-Furqan", 25, 69, "Yawma-l-Qiyaamah wa-yakhlud (Pada hari kiamat dan dia kekal)"),
    155: ("Asy-Syu'ara", 26, 82, "Yawma-d-Diin (Pada Hari Pembalasan)"),
    156: ("Asy-Syu'ara", 26, 87, "Yawma yub'atsuun (Pada hari mereka dibangkitkan)"),
    157: ("Asy-Syu'ara", 26, 88, "Yawma laa yanfa'u maalun (Hari ketika harta tidak lagi berguna)"),
    158: ("Asy-Syu'ara", 26, 135, " 'Adzaba Yawmin 'Adziim (Azab hari yang agung)"),
    159: ("Asy-Syu'ara", 26, 155, "Syirbu Yawmin ma'luum (Minuman pada hari yang ditentukan)"),
    160: ("Asy-Syu'ara", 26, 156, " 'Adzaba Yawmin 'Adziim (Azab hari yang agung)"),
    161: ("Asy-Syu'ara", 26, 189, " 'Adzaba Yawmi-zh-zhullah (Azab pada hari naungan/awan gelap)"),
    162: ("Asy-Syu'ara", 26, 189, " 'Adzabu Yawmin 'Adziim (Azab hari yang agung)"),
    163: ("An-Naml", 27, 83, "Wa-Yawma nahsyuru min kulli ummatin (Dan hari ketika Kami mengumpulkan dari tiap umat)"),
    164: ("An-Naml", 27, 87, "Wa-Yawma yunfakhu fi-sh-shuur (Dan hari ketika sangkakala ditiup)"),
    165: ("Al-Qashas", 28, 41, "Wa-Yawma-l-Qiyaamah laa yunsharuun (Dan pada hari kiamat mereka tidak ditolong)"),
    166: ("Al-Qashas", 28, 42, "Wa-Yawma-l-Qiyaamah hum mina-l-maqbuuhiin (Dan pada hari kiamat mereka dijauhkan)"),
    167: ("Al-Qashas", 28, 61, "Wa-huwa Yawma-l-Qiyaamah (Dan dia pada hari kiamat)"),
    168: ("Al-Qashas", 28, 62, "Wa-Yawma yunaadiihim (Dan hari ketika Allah memanggil mereka)"),
    169: ("Al-Qashas", 28, 65, "Wa-Yawma yunaadiihim fayaqulu (Dan hari ketika Allah memanggil mereka lalu bertanya)"),
    170: ("Al-Qashas", 28, 71, "Ilaa Yawmi-l-Qiyaamah (Sampai Hari Kiamat)"),
    171: ("Al-Qashas", 28, 72, "Ilaa Yawmi-l-Qiyaamah (Sampai Hari Kiamat)"),
    172: ("Al-Qashas", 28, 85, "Ilaa ma'aad (Kembali ke tempat kembali)"),
    173: ("Al-Ankabut", 29, 13, "Yawma-l-Qiyaamah 'ammaa kaanuu (Pada hari kiamat tentang apa yang mereka ada)"),
    174: ("Al-Ankabut", 29, 25, "Tsumma Yawma-l-Qiyaamah (Kemudian pada hari kiamat)"),
    175: ("Al-Ankabut", 29, 36, "Wa-l-Yawma-l-Aakhir (Dan Hari Akhir)"),
    176: ("Al-Ankabut", 29, 55, "Yawma yaghsyahumu-l-'adzab (Hari ketika azab menutup mereka)"),
    177: ("Ar-Rum", 30, 12, "Wa-Yawma taquumu-s-saa'atu (Dan hari ketika terjadinya kiamat)"),
    178: ("Ar-Rum", 30, 14, "Wa-Yawma taquumu-s-saa'atu Yawma-idzin (Dan hari ketika terjadinya kiamat, pada hari itu)"),
    179: ("Ar-Rum", 30, 43, "Min qabli an ya'tiya Yawmun (Sebelum datangnya suatu hari)"),
    180: ("Ar-Rum", 30, 55, "Wa-Yawma taquumu-s-saa'atu (Dan hari ketika terjadinya kiamat)"),
    181: ("Ar-Rum", 30, 56, "Ilaa Yawmi-l-ba'th (Sampai hari kebangkitan)"),
    182: ("Ar-Rum", 30, 56, "Fahaadza Yawmu-l-ba'th (Maka inilah hari kebangkitan)"),
    183: ("Luqman", 31, 33, "Wakhsyaw Yawman (Dan takutlah akan suatu hari)"),
    184: ("As-Sajdah", 32, 5, "Fii Yawmin kaana miqdaaruhu (Dalam sehari yang kadarnya)"),
    185: ("As-Sajdah", 32, 25, "Yawma-l-Qiyaamah fiimaa kuntum (Pada hari kiamat atas apa yang kamu)"),
    186: ("As-Sajdah", 32, 29, "Qul Yawma-l-fath (Katakanlah, pada hari kemenangan)"),
    187: ("Al-Ahzab", 33, 8, "Yawma laa yakhzaa (Hari ketika tidak dihinakan)"),
    188: ("Al-Ahzab", 33, 21, "Wa-l-Yawma-l-Aakhir (Dan Hari Akhir)"),
    189: ("Al-Ahzab", 33, 44, "Tahiyyatuhum Yawma yalqawnahu (Salam mereka pada hari mereka menemui-Nya)"),
    190: ("Al-Ahzab", 33, 66, "Yawma tuqallabu wujuuhuhum (Hari ketika wajah mereka dibolak-balik)"),
    191: ("Saba", 34, 30, "Mii'aadu Yawmin (Waktu yang dijanjikan pada suatu hari)"),
    192: ("Saba", 34, 40, "Wa-Yawma nahsyuruhum jamii'a (Dan hari ketika Kami mengumpulkan mereka semua)"),
    193: ("Saba", 34, 42, "Fa-l-Yawma laa yamliku (Maka pada hari ini tidak memiliki)"),
    194: ("Fatir", 35, 14, "Wa-Yawma-l-Qiyaamah yakfuruuna (Dan pada hari kiamat mereka mengingkari)"),
    195: ("Yasin", 36, 33, "Wa-ayatun lahumu-l-ardhu (Dan suatu tanda bagi mereka bumi)"),
    196: ("Yasin", 36, 54, "Fa-l-Yawma laa tudzlamu nafsun (Maka pada hari ini tidaklah dizalimi suatu jiwa)"),
    197: ("Yasin", 36, 55, "Inna ash-haaba-l-jannati-l-Yawma (Sesungguhnya penghuni surga pada hari ini)"),
    198: ("Yasin", 36, 59, "Wamtaazuu-l-Yawma (Dan berpisahlah kamu hari ini)"),
    199: ("Yasin", 36, 64, "Ishlawhaa-l-Yawma (Masuklah ke dalamnya hari ini)"),
    200: ("Yasin", 36, 65, "Al-Yawma nakhtimu 'alaa afwaahihim (Hari ini Kami kunci mulut mereka)"),
    # Lanjutan Database Yawm (201 - 250)
    201: ("Ash-Shaffat", 37, 20, "Haadza Yawmu-d-Diin (Inilah Hari Pembalasan)"),
    202: ("Ash-Shaffat", 37, 21, "Haadza Yawmu-l-fashli (Inilah Hari Keputusan)"),
    203: ("Ash-Shaffat", 37, 144, "Ilaa Yawmi yub'atsuun (Sampai hari mereka dibangkitkan)"),
    204: ("Sad", 38, 16, "Qabla Yawmi-l-hisaab (Sebelum Hari Perhitungan)"),
    205: ("Sad", 38, 26, "Bimaa nasuu Yawma-l-hisaab (Karena mereka melupakan Hari Perhitungan)"),
    206: ("Sad", 38, 53, "Li-Yawmi-l-hisaab (Untuk Hari Perhitungan)"),
    207: ("Sad", 38, 78, "Ilaa Yawmi-d-Diin (Sampai Hari Pembalasan)"),
    208: ("Sad", 38, 79, "Ilaa Yawmi yub'atsuun (Sampai hari mereka dibangkitkan)"),
    209: ("Sad", 38, 81, "Ilaa Yawmi-l-waqti-l-ma'luum (Sampai hari waktu yang ditentukan)"),
    210: ("Az-Zumar", 39, 13, " 'Adzaba Yawmin 'Adziim (Azab hari yang agung)"),
    211: ("Az-Zumar", 39, 24, "Yawma-l-Qiyaamah suu'a-l-'adzab (Pada hari kiamat azab yang buruk)"),
    212: ("Az-Zumar", 39, 31, "Yawma-l-Qiyaamah 'inda rabbikum (Pada hari kiamat di hadapan Tuhanmu)"),
    213: ("Az-Zumar", 39, 47, "Yawma-l-Qiyaamah maa lam yakunuu (Pada hari kiamat apa yang tidak mereka sangka)"),
    214: ("Az-Zumar", 39, 60, "Wa-Yawma-l-Qiyaamah taralladzina (Dan pada hari kiamat kamu melihat orang-orang yang...)"),
    215: ("Az-Zumar", 39, 67, "Jamii'an Yawma-l-Qiyaamah (Semuanya pada hari kiamat)"),
    216: ("Ghafir", 40, 15, "Li-yundzira Yawma-l-talaaq (Untuk memperingatkan tentang Hari Pertemuan)"),
    217: ("Ghafir", 40, 16, "Yawma hum baarizuun (Hari ketika mereka nampak jelas)"),
    218: ("Ghafir", 40, 16, "Li-manil mulku-l-Yawma (Milik siapakah kerajaan pada hari ini?)"),
    219: ("Ghafir", 40, 17, "Al-Yawma tujzaa kullu nafsin (Hari ini setiap jiwa diberi balasan)"),
    220: ("Ghafir", 40, 17, "Laa dhulma-l-Yawma (Tidak ada kezaliman pada hari ini)"),
    221: ("Ghafir", 40, 18, "Wa-andzirhum Yawma-l-aazifah (Peringatkanlah mereka akan Hari yang Dekat)"),
    222: ("Ghafir", 40, 27, "Bi-Yawmi-l-hisaab (Dengan Hari Perhitungan)"),
    223: ("Ghafir", 40, 29, "Ya qawmi lakumu-l-mulku-l-Yawma (Wahai kaumku, milikmulah kerajaan hari ini)"),
    224: ("Ghafir", 40, 30, "Mitsla Yawmi-l-ahzaab (Seperti hari kehancuran golongan yang bersekutu)"),
    225: ("Ghafir", 40, 32, "Wa-andzirhum Yawma-l-tanaad (Peringatkanlah mereka akan Hari Panggil-memanggil)"),
    226: ("Ghafir", 40, 33, "Yawma tuwalluuna mudbiriin (Hari ketika kamu lari ke belakang)"),
    227: ("Ghafir", 40, 46, "Wa-Yawma taquumu-s-saa'atu (Dan pada hari terjadinya kiamat)"),
    228: ("Ghafir", 40, 49, "Yawman mina-l-'adzab (Sehari dari azab)"),
    229: ("Ghafir", 40, 51, "Wa-Yawma yaquumu-l-asyhaad (Dan pada hari bangkitnya para saksi)"),
    230: ("Ghafir", 40, 52, "Yawma laa yanfa'u-dh-dhaalimiin (Hari ketika tidak berguna bagi orang zalim)"),
    231: ("Fushshilat", 41, 19, "Wa-Yawma yuhsyaru a'daa-u-llah (Dan hari ketika musuh Allah dikumpulkan)"),
    232: ("Fushshilat", 41, 47, "Wa-Yawma yunaadiihim (Dan hari ketika Allah memanggil mereka)"),
    233: ("Asy-Syura", 42, 7, "Li-tundzira Yawma-l-jam'i (Untuk memperingatkan tentang Hari Berkumpul)"),
    234: ("Asy-Syura", 42, 45, "Yawma-l-Qiyaamah alaa inna (Pada hari kiamat, ingatlah sesungguhnya...)"),
    235: ("Asy-Syura", 42, 47, "Min qabli an ya'tiya Yawmun (Sebelum datangnya suatu hari)"),
    236: ("Az-Zukhruf", 43, 39, "Wa-lan yanfa'akumu-l-Yawma (Dan tidak akan memberi manfaat kepadamu hari ini)"),
    237: ("Az-Zukhruf", 43, 41, "Fa-innaa minhum muntaqimuun (Maka Kami akan menghukum mereka)"),
    238: ("Az-Zukhruf", 43, 65, "Min 'adzabi Yawmin aliim (Dari azab hari yang pedih)"),
    239: ("Az-Zukhruf", 43, 68, "Laa khawfun 'alaykumu-l-Yawma (Tidak ada ketakutan bagimu hari ini)"),
    240: ("Az-Zukhruf", 43, 83, "Hattaa yulaaquu Yawmahum (Hingga mereka menemui hari mereka)"),
    241: ("Ad-Dukhan", 44, 10, "Fa-rtaqib Yawma ta'ti-s-samaa-u (Maka tunggulah hari ketika langit membawa...)"),
    242: ("Ad-Dukhan", 44, 16, "Yawma nabthisyu-l-bathsyata (Hari ketika Kami menghantam dengan hantaman keras)"),
    243: ("Ad-Dukhan", 44, 40, "Inna Yawma-l-fashli miiqaatuhum (Sesungguhnya Hari Keputusan adalah waktu yang dijanjikan)"),
    244: ("Ad-Dukhan", 44, 41, "Yawma laa yughnii mawlan (Hari ketika seorang pelindung tidak berguna)"),
    245: ("Al-Jathiyah", 45, 14, "Li-yajziya qawman (Untuk memberi balasan pada suatu kaum)"),
    246: ("Al-Jathiyah", 45, 17, "Yawma-l-Qiyaamah fiimaa kaanuu (Pada hari kiamat atas apa yang mereka...)"),
    247: ("Al-Jathiyah", 45, 26, "Ilaa Yawmi-l-Qiyaamah laa rayba (Sampai Hari Kiamat yang tidak ada keraguan)"),
    248: ("Al-Jathiyah", 45, 27, "Wa-Yawma taquumu-s-saa'atu (Dan pada hari terjadinya kiamat)"),
    249: ("Al-Jathiyah", 45, 34, "Wa-qiila-l-Yawma nansaakum (Dan dikatakan: Hari ini Kami melupakanmu)"),
    250: ("Al-Jathiyah", 45, 35, "Fa-l-Yawma laa yukhrajuuna (Maka pada hari ini mereka tidak dikeluarkan)"),
    # Lanjutan Database Yawm (251 - 300)
    251: ("Al-Ahqaf", 46, 20, "Wa-Yawma yu'radhulladzina kafaruu (Dan hari ketika orang kafir dihadapkan ke neraka)"),
    252: ("Al-Ahqaf", 46, 20, "Al-Yawma tujzawna 'adzabal huun (Hari ini kamu dibalas dengan azab yang menghinakan)"),
    253: ("Al-Ahqaf", 46, 21, "Min bayni yadayhi wa min khalfih (Peringatan dari masa sebelumnya dan sesudahnya)"),
    254: ("Al-Ahqaf", 46, 34, "Wa-Yawma yu'radhulladzina kafaruu (Dan hari ketika orang kafir dihadapkan ke neraka)"),
    255: ("Al-Ahqaf", 46, 35, "Ka-annahum Yawma yarawnaha (Seolah-olah mereka pada hari melihatnya)"),
    256: ("Muhammad", 47, 18, "An ta'tiyahum baghtatan (Bahwa kiamat akan datang mendadak)"),
    257: ("Al-Fath", 48, 12, "Wa kuntum qawman buuraa (Dan kamu adalah kaum yang binasa)"),
    258: ("Al-Hujurat", 49, 12, "A-yuhibbu ahadukum an ya'kula (Apakah salah seorang kamu suka memakan...)"),
    259: ("Qaf", 50, 19, "Wa jaa-at sakratul mawti (Dan datanglah sakaratul maut)"),
    260: ("Qaf", 50, 20, "Dzaalika Yawmul wa'iid (Itulah Hari yang Diancamkan)"),
    261: ("Qaf", 50, 22, "Fa kasyafna 'anka ghitha-ak (Maka Kami singkapkan tutup matamu)"),
    262: ("Qaf", 50, 30, "Yawma naquulu li-jahannama (Hari ketika Kami bertanya kepada Jahanam)"),
    263: ("Qaf", 50, 34, "Dzaalika Yawmul khuluud (Itulah Hari Kekekalan)"),
    264: ("Qaf", 50, 41, "Yawma yunaadil munaadi (Hari ketika penyeru memanggil)"),
    265: ("Qaf", 50, 42, "Yawma yasma'uunash shayhata (Hari ketika mereka mendengar teriakan)"),
    266: ("Qaf", 50, 42, "Dzaalika Yawmul khuruuj (Itulah Hari Keluar dari kubur)"),
    267: ("Qaf", 50, 44, "Yawma tasyaqqaqul ardhu (Hari ketika bumi terbelah)"),
    268: ("Adz-Dzariyat", 51, 12, "Ayyaana Yawmud Diin (Kapankah Hari Pembalasan itu?)"),
    269: ("Adz-Dzariyat", 51, 13, "Yawma hum 'alan naari (Hari ketika mereka dibakar di atas neraka)"),
    270: ("Adz-Dzariyat", 51, 60, "Min Yawmihimulladzii yuu'aduun (Dari hari yang dijanjikan kepada mereka)"),
    271: ("At-Tur", 52, 9, "Yawma tamuurus samaa-u (Hari ketika langit berguncang)"),
    272: ("At-Tur", 52, 13, "Yawma yuda''uuna ilaa naari (Hari ketika mereka didorong ke neraka)"),
    273: ("At-Tur", 52, 46, "Yawma laa yughnii 'anhum (Hari ketika tipu daya tak berguna)"),
    274: ("An-Najm", 53, 57, "Azifatil azifah (Telah dekat hari kiamat)"),
    275: ("Al-Qamar", 54, 6, "Yawma yad'ul munaadi (Hari ketika penyeru memanggil)"),
    276: ("Al-Qamar", 54, 8, "Yaqulul kaafiruuna haadza Yawmun 'asir (Orang kafir berkata: Ini hari yang sulit)"),
    277: ("Al-Qamar", 54, 19, "Fii Yawmi nahsin mustamir (Pada hari nahas yang terus menerus)"),
    278: ("Al-Qamar", 54, 48, "Yawma yushabuuna fin naari (Hari ketika mereka diseret ke neraka)"),
    279: ("Ar-Rahman", 55, 29, "Kulla Yawmin Huwa fii sya'n (Setiap hari Dia dalam kesibukan/urusan)"),
    280: ("Al-Waqi'ah", 56, 50, "Ilaa miiqaati Yawmin ma'luum (Sampai waktu pada hari yang ditentukan)"),
    281: ("Al-Waqi'ah", 56, 56, "Haadza nuzuluhum Yawmad Diin (Inilah hidangan mereka pada Hari Pembalasan)"),
    282: ("Al-Hadid", 57, 12, "Yawma taral mu'miniina (Hari ketika kamu melihat orang mukmin...)"),
    283: ("Al-Hadid", 57, 12, "Busyraakumul Yawma jannaat (Kabar gembira bagimu hari ini adalah surga)"),
    284: ("Al-Hadid", 57, 13, "Yawma yaquulul munaafiquuna (Hari ketika orang munafik berkata...)"),
    285: ("Al-Hadid", 57, 15, "Fal-Yawma laa yu'khadzu minkum (Maka hari ini tidak diambil tebusan darimu)"),
    286: ("Al-Mujadilah", 58, 6, "Yawma yab'atsuhumullahu jamii'a (Hari ketika Allah membangkitkan mereka semua)"),
    287: ("Al-Mujadilah", 58, 7, "Wa laa adnaa min dzaalika (Dan tidak ada yang lebih sedikit dari itu)"),
    288: ("Al-Mujadilah", 58, 18, "Yawma yab'atsuhumullahu jamii'a (Hari ketika Allah membangkitkan mereka semua)"),
    289: ("Al-Hasyr", 59, 18, "Wa-l-tanzhur nafsun maa qaddamat lighad (Hendaklah setiap jiwa memperhatikan apa yang diperbuat untuk esok hari)"),
    290: ("Al-Mumtahanah", 60, 3, "Yawmal Qiyaamathi yafshilu (Pada hari kiamat Dia memutuskan...)"),
    291: ("Al-Jumu'ah", 62, 9, "Idzaa nuudiya lish-shalaati min Yawmil Jumu'ah (Apabila diseru untuk shalat pada hari Jumat)"),
    292: ("At-Taghabun", 64, 9, "Yawma yajma'ukum li-Yawmil Jam'i (Hari ketika Dia mengumpulkanmu pada Hari Berkumpul)"),
    293: ("At-Taghabun", 64, 9, "Dzaalika Yawmut Taghaabun (Itulah Hari Ditampakkannya Kesalahan)"),
    294: ("At-Tahrim", 66, 7, "Laa ta'tadzirul Yawma (Janganlah kamu minta maaf hari ini)"),
    295: ("At-Tahrim", 66, 8, "Yawma laa yukhzillaahullaahu (Hari ketika Allah tidak menghinakan...)"),
    296: ("Al-Mulk", 67, 15, "Wa ilayhin nusyuur (Dan kepada-Nya lah tempat kembali)"),
    297: ("Al-Qalam", 68, 39, "Ilaa Yawmil Qiyaamah (Sampai Hari Kiamat)"),
    298: ("Al-Qalam", 68, 42, "Yawma yuksyafu 'an saaqin (Hari ketika betis disingkapkan/penderitaan memuncak)"),
    299: ("Al-Haqqah", 69, 35, "Falaysal Yawma haahunaa (Maka hari ini di sini tidak ada...)"),
    300: ("Al-Ma'arij", 70, 4, "Fii Yawmin kaana miqdaaruhu (Dalam sehari yang kadarnya 50 ribu tahun)"),
    # Lanjutan Database Yawm (301 - 365) - TAHAP FINAL
    301: ("Al-Ma'arij", 70, 8, "Yawma takuunus samaa-u kal-muhl (Pada hari ketika langit seperti lelehan logam)"),
    302: ("Al-Ma'arij", 70, 43, "Yawma yakhrujuuna minal ajdaatsi (Hari ketika mereka keluar dari kubur)"),
    303: ("Al-Ma'arij", 70, 44, "Dzaalikal Yawmulladzii yuu'aduun (Itulah hari yang dijanjikan kepada mereka)"),
    304: ("Nuh", 71, 1, "Min qabli an ya'tiyahum 'adzabun (Sebelum datang kepada mereka azab)"),
    305: ("Al-Muzzammil", 73, 14, "Yawma tarjupul ardhu wal jibaal (Hari ketika bumi dan gunung berguncang)"),
    306: ("Al-Muzzammil", 73, 17, "Yawman yaj'alul wildaana syiiba (Hari yang menjadikan anak-anak beruban)"),
    307: ("Al-Muddatstsir", 74, 9, "Fadzaalika Yawma-idzin Yawmun 'Asiir (Maka itulah hari yang sangat sulit)"),
    308: ("Al-Muddatstsir", 74, 46, "Nukadzdzibu bi-Yawmid Diin (Kami mendustakan Hari Pembalasan)"),
    309: ("Al-Qiyamah", 75, 1, "Laa uqsimu bi-Yawmil Qiyaamah (Aku bersumpah dengan Hari Kiamat)"),
    310: ("Al-Qiyamah", 75, 6, "Ayyaana Yawmul Qiyaamah (Kapankah Hari Kiamat itu?)"),
    311: ("Al-Insan", 76, 7, "Yawman kaana syarruhu mustathiira (Suatu hari yang azabnya merata di mana-mana)"),
    312: ("Al-Insan", 76, 10, "Yawman 'abuusan qamthariira (Hari yang penuh kesulitan dan penderitaan)"),
    313: ("Al-Insan", 76, 11, "Syarra dzaalikal Yawm (Kejahatan hari tersebut)"),
    314: ("Al-Insan", 76, 27, "Wa yadzaruna waraa-ahum Yawman tsaqiila (Dan mereka tinggalkan di belakang mereka hari yang berat)"),
    315: ("Al-Mursalat", 77, 12, "Li-ayyi Yawmin ujjilat (Untuk hari manakah ditunda?)"),
    316: ("Al-Mursalat", 77, 13, "Li-Yawmil Fashl (Untuk Hari Keputusan)"),
    317: ("Al-Mursalat", 77, 14, "Maa Yawmul Fashl (Apakah Hari Keputusan itu?)"),
    318: ("Al-Mursalat", 77, 35, "Haadza Yawmu laa yanthiquun (Inilah hari ketika mereka tidak dapat berbicara)"),
    319: ("Al-Mursalat", 77, 38, "Haadza Yawmul Fashl (Inilah Hari Keputusan)"),
    320: ("An-Naba", 78, 17, "Inna Yawmal Fashli kaana miiqaata (Sesungguhnya Hari Keputusan adalah waktu yang ditetapkan)"),
    321: ("An-Naba", 78, 18, "Yawma yunfakhu fish-shuuri (Hari ketika sangkakala ditiup)"),
    322: ("An-Naba", 78, 38, "Yawma yaquumur ruuhu wal malaa-ikah (Hari ketika ruh dan malaikat berdiri)"),
    323: ("An-Naba", 78, 39, "Dzaalikal Yawmul Haqq (Itulah hari yang pasti terjadi)"),
    324: ("An-Naba", 78, 40, "Yawma yanzhurul mar-u maa qaddamat yadaah (Hari ketika manusia melihat apa yang telah diperbuat tangannya)"),
    325: ("An-Nazi'at", 79, 35, "Yawma yatadzakkarul insaanu (Hari ketika manusia teringat)"),
    326: ("An-Nazi'at", 79, 46, "Ka-annahum Yawma yarawnahaa (Seolah-olah mereka pada hari melihatnya)"),
    327: ("'Abasa", 80, 34, "Yawma yafirrul mar-u min akhiih (Hari ketika manusia lari dari saudaranya)"),
    328: ("At-Takwir", 81, 1, "Idzasy syamsu kuwwirat (Apabila matahari digulung)"),
    329: ("Al-Infitar", 82, 15, "Yashlawnahaa Yawmad Diin (Mereka memasukinya pada Hari Pembalasan)"),
    330: ("Al-Infitar", 82, 17, "Maa Yawmud Diin (Apakah Hari Pembalasan itu?)"),
    331: ("Al-Infitar", 82, 18, "Maa Yawmud Diin (Apakah Hari Pembalasan itu?)"),
    332: ("Al-Infitar", 82, 19, "Yawma laa tamliku nafsun (Hari ketika seseorang tidak berdaya)"),
    333: ("Al-Muthaffifin", 83, 5, "Li-Yawmin 'Adziim (Untuk hari yang agung)"),
    334: ("Al-Muthaffifin", 83, 6, "Yawma yaquumun naasu (Hari ketika manusia berdiri menghadap Tuhan)"),
    335: ("Al-Muthaffifin", 83, 11, "Yukadzdzibuna bi-Yawmid Diin (Mereka mendustakan Hari Pembalasan)"),
    336: ("Al-Muthaffifin", 83, 34, "Fal-Yawmalladzina aamanuu (Maka pada hari ini orang-orang beriman...)"),
    337: ("Al-Inshiqaq", 84, 1, "Idzas samaa-un syaqqat (Apabila langit terbelah)"),
    338: ("Al-Buruj", 85, 2, "Wal Yawmil Maw'uud (Dan demi hari yang dijanjikan)"),
    339: ("Al-Thariq", 86, 9, "Yawma tublas saraa-ir (Hari ketika ditampakkan segala rahasia)"),
    340: ("Al-Ghashiyah", 88, 1, "Hal ataaka hadiitsul ghaasyiyah (Sudahkah datang kepadamu berita tentang hari kiamat?)"),
    341: ("Al-Fajr", 89, 23, "Wa jii-a Yawma-idzin bi-jahannama (Dan pada hari itu didatangkan neraka Jahanam)"),
    342: ("Al-Fajr", 89, 23, "Yawma-idzin yatadzakkarul insaanu (Pada hari itu manusia menjadi ingat)"),
    343: ("Al-Balad", 90, 14, "Aw ith-'aamun fii Yawmin dzii masghabah (Atau memberi makan pada hari kelaparan)"),
    344: ("Asy-Syams", 91, 1, "Wasy syamsi wa dhuhaahaa (Demi matahari dan cahayanya)"),
    345: ("Al-Lail", 92, 1, "Wal layli idzaa yaghshaa (Demi malam apabila menutupi)"),
    346: ("Ad-Duha", 93, 1, "Wadh dhuhaa (Demi waktu dhuha)"),
    347: ("Al-Insyirah", 94, 1, "Alam nasyrah laka shadrak (Bukankah Kami telah melapangkan dadamu?)"),
    348: ("At-Tin", 95, 1, "Wat tiini waz zaytuun (Demi buah tin dan zaitun)"),
    349: ("Al-'Alaq", 96, 1, "Iqra' bismi rabbikalladzii khalaq (Bacalah dengan nama Tuhanmu)"),
    350: ("Al-Qadr", 97, 1, "Innaa anzalnaahu fii laylatil qadr (Kami menurunkannya pada malam kemuliaan)"),
    351: ("Al-Bayyinah", 98, 1, "Lam yakunilladzina kafaruu (Orang kafir tidak akan meninggalkan...)"),
    352: ("Al-Zalzalah", 99, 4, "Yawma-idzin tuhadditsu akhbaarahaa (Pada hari itu bumi menceritakan beritanya)"),
    353: ("Al-Zalzalah", 99, 6, "Yawma-idzin yashdurun naasu (Pada hari itu manusia keluar dalam keadaan berkelompok)"),
    354: ("Al-'Adiyat", 100, 1, "Wal 'aadiyaati dhabhaa (Demi kuda perang yang berlari kencang)"),
    355: ("Al-Qari'ah", 101, 4, "Yawma yakuunun naasu kal faraasyil mabtsuuts (Hari ketika manusia seperti laron yang beterbangan)"),
    356: ("At-Takatsur", 102, 8, "Tsumma latus-alunna Yawma-idzin (Kemudian kamu benar-benar akan ditanya pada hari itu)"),
    357: ("Al-'Asr", 103, 1, "Wal 'ashr (Demi masa)"),
    358: ("Al-Humazah", 104, 1, "Waylun likulli humazatin lumazah (Celakalah bagi setiap pengumpat lagi pencela)"),
    359: ("Al-Fil", 105, 1, "Alam tara kayfa fa'ala rabbuka (Tidakkah kamu perhatikan bagaimana Tuhanmu bertindak)"),
    360: ("Quraysh", 106, 1, "Li-ilaafi quraysyin (Karena kebiasaan orang Quraisy)"),
    361: ("Al-Ma'un", 107, 1, "Ara-aytalladzii yukadzdzibu bid diin (Tahukah kamu orang yang mendustakan agama?)"),
    362: ("Al-Kautsar", 108, 1, "Innaa a'thaynaakal kautsar (Sesungguhnya Kami memberimu nikmat yang banyak)"),
    363: ("Al-Kafirun", 109, 1, "Qul yaa ayyuhal kaafiruun (Katakanlah: Wahai orang-orang kafir)"),
    364: ("An-Nashr", 110, 1, "Idzaa jaa-a nashrullaahi wal fath (Apabila telah datang pertolongan Allah dan kemenangan)"),
    365: ("An-Nas", 114, 6, "Minal jinnati wan naas (Dari golongan jin dan manusia)")
}
